# Generated by Django 4.0b1 on 2021-11-04 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
