# Generated by Django 4.0 on 2021-12-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_remove_expense_categories_category_color_and_more"),
    ]

    database_operations = [
        migrations.AlterModelTable("Category", "categories_category"),
    ]

    state_operations = [migrations.DeleteModel("Category")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
