# Generated by Django 4.0 on 2021-12-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
    ]
